service_tuple=("HTTP","HTTPS","SMB","DNS")
print(f"Tuples has the following elements:{service_tuple}")
print("\n Trying to remove elements")
service_list= list(service_tuple)
print(f"\n Converted Service List {service_list}")
print(f"\n Type of service list is {type(service_list)}")
service_list.append('SMTP')
service_tuple=tuple(service_list)
print(f"\n appended tuple is {service_tuple}")