port_list=[25,443,80,145,337]
print(f"Default port list is {port_list}")
print("\nAdding a port")
port_list.append(445)
print(f"\nAppended port list is {port_list}")
print("\nRemoving 145 from the list")
port_list.remove(145)
print(f"\nRemoved 145 from the list is {port_list}")
print("\nSorting the list")
port_list.sort()
print(f"\nSorted list is {port_list}")
print("\n reverse sorting")
port_list.sort(reverse=True)
print(f"\n Reversed Sorted list is {port_list}")
